M48
; DRILL file {KiCad (6.0.1)} date Thu May  5 21:04:39 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-05T21:04:39+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.2106
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.2559
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.3543
%
G90
G05
T1
X7.4086Y-1.0803
X7.6362Y-1.0803
T2
X1.8142Y-2.6
X7.522Y-2.8724
T3
X7.0772Y-4.6083
X7.9709Y-4.6083
T4
X7.522Y-3.2713
T0
M30
